### PR TITLE
Created a section for the slack channel and added the link.

### LINKED ISSUE #22: We need to add a section with our Slack Channel! <3
Hey everyone!
@ZahraB21 , @helgakern , @rebecatschiedel , @CarolDill , @kaileegiles 

I've created a [slack channel](https://join.slack.com/t/webdevpath/shared_invite/zt-je2zuuja-zlQr2_YpFP_9zuyGcKeYGg) for us and we need to add a section with it in our repository.

Hope to see you all there!

**HOT TIP:**
_When submitting a Pull Request to solve an issue, mention the issue number on the PR description (not on the title) so that they both get linked.
You can use something like "Solves #21", "Referent to the issue #21", or Closes #21. By using Closes and the issue number, GitHub will automatically close the issue when the PR that is addressing it is merged into the master._

### PR DESCRIPTION
**Pull request by helgakern**
Hi everyone!

I've created a section for the Slack channel and added the link. Closes #22.

### CODE REVIEW

**Review by MarianaSouza — CHANGES_REQUESTED** [review]
Thanks for this PR @helgakern ! :D

Could you please make the PR title more descriptive and mention the issue (Solves #22 or Closes #22) on the PR description?

**Comment by helgakern** [comment]
Hi Mariana!
=)
Sure thing!

**Comment by MarianaSouza** [comment]
> Hi Mariana!
> =)
> Sure thing!

Awesome, @helgakern ! Thanks!
The only thing missing now is to move the part Closes #22 inside the PR description like this:

tempsnip

**Comment by helgakern** [comment]
=D

**Review by MarianaSouza — APPROVED** [review]

**Comment by MarianaSouza** [comment]
> =D

Thanks @helgakern !
I removed the "Closes" mention from the PR title as well - we usually mention it only on the description - and it's all yours to merge!

**Pull request merged**
