### PR TITLE
Editing Wordpress section to display items as list items with bullets

### PR DESCRIPTION
**Pull request by ZahraB21**
This pull request displays the Wordpress links as bullet points for better readability.

This is related to the issue #20.

### CODE REVIEW

**Review by MarianaSouza — CHANGES_REQUESTED** [review]
Hey @ZahraB21 ! Thanks for this PR!
There is still this final link to fix :\* [WordPress Plugin Development](https://youtu.be/mm9aQiLEa10)
I think you could work a little bit more on your PR description to make it clearer.
A nice tip to test your documentation PR's is that by clicking over your branch link on the top of the page (attached), you check how your changes are affecting the project.

image

**Comment by ZahraB21** [comment]
@MarianaSouza Thank you. I have fixed the issue with the link and should now show the link as another list item under Wordpress section.

**Review by MarianaSouza — APPROVED** [review]
Thanks, @ZahraB21 ! Looks great! 👯 
It's all yours to merge.

**Comment by ZahraB21** [comment]
Thanks @MarianaSouza .

**Pull request merged**
