### PR TITLE
Adding Wordpress section to the course

### PR DESCRIPTION
**Pull request by ZahraB21**
This is referencing the issue #6. 
I am adding a section for WordPress (WP) in the ReadMe file for people who are seeking more knowledge about it. It includes a link for WordPress Theme development and another link for plugin development.

### CODE REVIEW

**Review by rebecatschiedel — DISMISSED** [review]

**Comment by MarianaSouza** [comment]
Hey @ZahraB21 ,

Is this PR ready for review already?

There are some things you still need to work on, such as a detailed description as per the previous feedback " In this PR, the goal is to add a WordPress section as requested in the issue #6 ...". It's important to tell the story of the change here. Also, you always start assigning yourself to your PR's since you'll be the one responsible for merging it. Please add me as a reviewer of all PR for now.

Finally, when you create a PR and it's not ready yet, you can always convert it into "Draft" or leave a comment saying it's still in progress. That option is below the "Reviewers".

pr-improvments

**Review by MarianaSouza — CHANGES_REQUESTED** [review]
Hey @ZahraB21 ,

Can you please add a detailed description as per the previous feedback " In this PR, the goal is to add a WordPress section as requested in the issue #6 ...". It's important to tell the story of the change here. 
Thanks!

**Comment by ZahraB21** [comment]
> Hey @ZahraB21 ,
> 
> Can you please add a detailed description as per the previous feedback " In this PR, the goal is to add a WordPress section as requested in the issue #6 ...". It's important to tell the story of the change here.
> Thanks!

Hey @MarianaSouza 
I have added more details in the description section of PR. Please have a look and let me know. 
Thanks you again.

**Review by MarianaSouza — APPROVED** [review]
Thanks, @ZahraB21 ! Looks great!

**Pull request merged**
