### PR TITLE
Adding the section books

### PR DESCRIPTION
**Pull request by rebecatschiedel**
Add a new section called Books, section-book/CommandLine, section-books/JavaScript(JS) and section-books/Programming.

### CODE REVIEW

**Comment by MarianaSouza** [comment]
Hey @rebecatschiedel ,

That's a great idea to add a "Books" section. Thanks!
We should try following the branch guidelines we see in the introduction section, which means your branch should be called something like section-course/books, for example. It's pretty common when you're an in a team, having to follow naming guidelines. Could you please rename the branch? https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/

Also, the PR title should present the general idea of the activity you are doing here, such as "Adding the section books"

**Review by MarianaSouza — CHANGES_REQUESTED** [review]
Hey @rebecatschiedel ,

That's a great idea to add a "Books" section. Thanks!
We should try following the branch guidelines we see in the introduction section, which means your branch should be called something like section-course/books, for example. It's pretty common when you're an in a team, having to follow naming guidelines. Could you please rename the branch? https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/

Also, the PR title should present the general idea of the activity you are doing here, such as "Adding the section books"

**Comment by rebecatschiedel** [comment]
Hi @MarianaSouza,

Thank you for the explanation and for the link, both were very useful!!

**Comment by rebecatschiedel** [comment]
I opened a new pull request because I messed up my forked code while i was trying to rename it. It was a great opportunity to learn a lot of new things.

**Pull request closed without merging**
