### PR TITLE
Adding CS50 and CS50-beyond courses under Courses and Certifications

### PR DESCRIPTION
**Pull request by rebecatschiedel**
Referent to the issue #12. 
This PR aims to add the section-course/CS50-CS50Beyond with the open ware courses from Harvard. CS50 is a great introductory course and CS50 beyond follows it with web development material.

### CODE REVIEW

**Review by MarianaSouza — CHANGES_REQUESTED** [review]
Hi @rebecatschiedel ,
Thanks for adding this section!

1 Could you please link the PR description with the Issue as described on the issue itself?
https://github.com/MarianaSouza/web-dev-path/issues/12
issue-12-png

2 Also, since you are adding two links, could you please elaborate on the PR story? The PR should describe to someone who knows nothing about it why you're doing it. A good start could be: "This PR aims to add two courses related to {...} because {...}".

Please let me know if you have any questions! :)

**Review by helgakern — COMMENTED** [review]
It looks good for me.

**Comment by MarianaSouza** [comment]
Hey @rebecatschiedel !  :)
Any questions so far about the changes here?
After doing those changes, could you please pull from master to your branch and commit it so that we solve the conflict that is preventing the merge?
Please let me know if you have any questions!

**Comment by rebecatschiedel** [comment]
Hello @MarianaSouza, sorry for my absence. Unfortunately, I still don't have my computer here and I was struggling to learn how to do things with the cellphone. Thank you for the patience. I am back now!

**Comment by rebecatschiedel** [comment]
@MarianaSouza I don't know how to update my branch from master in github without using git, and i can't use git on my phone. Do you have any suggestions?

**Comment by MarianaSouza** [comment]
> @MarianaSouza I don't know how to update my branch from master in github without using git, and i can't use git on my phone. Do you have any suggestions?

Hey @rebecatschiedel :)

Thanks for adjusting the PR and for letting me know about your current situation. 

Since you forked the repository (not cloned it) I can't have access to your repo local branch. That's totally fine to have forked it though, so, don't worry - whenever you have a computer available, you git pull from master to your local branch and then commit that to this PR.  Does it make sense? Pls let me know if you have more questions ;)

**Comment by rebecatschiedel** [comment]
Hello everyone!! :)
@MarianaSouza is there anything else to fix??

**Review by MarianaSouza — APPROVED** [review]
This looks great, @rebecatschiedel ! :D
All yours to merge!

**Pull request merged**
