### PR TITLE
Adding a section called: Launching A Website

### PR DESCRIPTION
**Pull request by ZahraB21**
I am adding a new section called 'Launching a website', providing details about domains, DNS, hosting and publishing a website.

This is referring to the issue #21.

### CODE REVIEW

**Review by MarianaSouza — CHANGES_REQUESTED** [review]
Hey @ZahraB21 ! Thanks so much for this PR :)
Since Launching a Website is not so related to oneself Presentation, I guess we should create a new section, maybe above the Presentation section, to add it, what do you think?

**Comment by CarolDill** [comment]
> Hey @ZahraB21 ! Thanks so much for this PR :)
> Since Launching a Website is not so related to oneself Presentation, I guess we should create a new section, maybe above the Presentation section, to add it, what do you think?

Hi Mariana!

Maybe a section called "Guides"?

What you guys think?

**Comment by ZahraB21** [comment]
@MarianaSouza Sure, I can place it outside of Presentation. I was thinking that they might use it for their portfolio and that is also a part of representing themselves, that's why I put it there.

@CarolDill I think Guides is a suitable title name.

**Comment by MarianaSouza** [comment]
> @MarianaSouza Sure, I can place it outside of Presentation. I was thinking that they might use it for their portfolio and that is also a part of representing themselves, that's why I put it there.
> 
> @CarolDill I think Guides is a suitable title name.

Hey @ZahraB21 , this topic is more related to the server admin, so I'd call the section Publishing a Web Product or Launching a Website. Guides sounds too generic for me. Thanks ;)

**Comment by ZahraB21** [comment]
> > @MarianaSouza Sure, I can place it outside of Presentation. I was thinking that they might use it for their portfolio and that is also a part of representing themselves, that's why I put it there.
> > @CarolDill I think Guides is a suitable title name.
> 
> Hey @ZahraB21 , this new section will be more related to the server admin, so I'd call the section Publishing a Web Product or Launching a Website. There, we could add all the guides related to DNS, hosting, and domain. Guides only sounds too generic for me. Thanks ;)

@MarianaSouza I have changed the Guides title to Publish a Web Product. I think its ready to be merged.

**Comment by ZahraB21** [comment]
> Hey @ZahraB21 ! Thanks so much for this PR :)
> Since Launching a Website is not so related to oneself Presentation, I guess we should create a new section, maybe above the Presentation section, to add it, what do you think?

Its outside of Presentation now and under Publishing a Web Product.

**Review by MarianaSouza — CHANGES_REQUESTED** [review]
Hi @ZahraB21 , Thanks for this PR!

Can you please change the tutorial kink attached to "How to Put a Website Online: Template, Coding, Domain, Hosting, and DNS", which is the original video name?

image

Let's make the titles consistent to the sources for the users whenever possible. Thanks!

**Comment by ZahraB21** [comment]
> Hi @ZahraB21 , Thanks for this PR!
> 
> Can you please change the tutorial kink attached to "How to Put a Website Online: Template, Coding, Domain, Hosting, and DNS", which is the original video name?
> 
> image
> 
> Let's make the titles consistent to the sources for the users whenever possible. Thanks!

I have replaced the text to original one. I think its good to go.

**Review by MarianaSouza — APPROVED** [review]
Looks great,  @ZahraB21 !

**Pull request merged**
