### PR TITLE
Add a tutorial section about PR creation

### PR DESCRIPTION
**Pull request by MarianaSouza**
In this PR, a section with videos about the PR creation is being added to the repository. It will contain videos showing how to [branch out from master](https://www.loom.com/share/77c3bea45d86428a86c897ac3ccaacc4), how to [create your first commit and PR](https://www.loom.com/share/04e326b873db4af7a4ce86c74183d554), how to [fix the PR title](https://www.loom.com/share/58feae54c4d04a2e908d5fe41dc262e9), how to [add a good description and link it with the issue](https://www.loom.com/share/bf775cb7503c42129ab5f7715b094c53), and how to [merge a PR](https://www.loom.com/share/de0eaa9cdcd34d8bac491cd8955f4883).

This is related to issue #17.

### CODE REVIEW

**Comment by MarianaSouza** [comment]
Hi everybody <3!
@ZahraB21 / @helgakern / @rebecatschiedel / @kaileegiles / @CarolDill 

I've created this PR with some videos with detailed information about the PR creation process. I invite you to watch the videos and I'd love to hear your feedback!

**Comment by CarolDill** [comment]
Hi Mariana,

The videos are really good... I was wondering if we will have a separated section explaining how to merge the Pull Request.

**Review by CarolDill — COMMENTED** [review]
Just waiting to know about merging.
For me it's well explained.

**Comment by MarianaSouza** [comment]
> Hi Mariana,
> 
> The videos are really good... I was wondering if we will have a separated section explaining how to merge the Pull Request.

Hey @CarolDill ! :)
Adding a video showing how to merge is a good idea! Thanks for suggesting it.
I'm just going to wait a few days until I receive more feedback with points I could address in that video and then I'll record it.

**Comment by ZahraB21** [comment]
Hi Mariana, 

Thank you for sharing the videos. It cleared things for me specially about the different between the PR and Issues. A merging video is an excellent idea to make it a complete! 👍

**Review by ZahraB21 — APPROVED** [review]
Hi Mariana,

Thank you for sharing the videos. It cleared things for me specially about the different between the PR and Issues. A merging video is an excellent idea to make it a complete! 👍

**Comment by ZahraB21** [comment]
Hi Mariana, 
I have merged my pull request and created a video about it. Here is the link: https://www.loom.com/share/de0eaa9cdcd34d8bac491cd8955f4883

I hope everything is clear and descriptive in the video.
Thanks.

**Comment by kaileegiles** [comment]
Videos are great Mariana & Zahra! Thanks so much for creating this hub of resources - so awesome for everyone :)

**Review by helgakern — COMMENTED** [review]
Good idea about the videos!

**Comment by MarianaSouza** [comment]
Hey @ZahraB21  :D

Thanks so much for the video! <3 I've just added it and, by doing that, all your approvals were canceled on this PR. Would you mind approving it again?

The same and sorry, girls, @CarolDill / @helgakern / @kaileegiles . Would you mind to approve this PR again when you have a change, please? You can learn more about the reviewing process here:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews

Thanks <3

**Review by ZahraB21 — APPROVED** [review]
Looks great Mariana. Thanks for adding the PR videos.

**Review by helgakern — COMMENTED** [review]
Hi Mariana, I'm reviewing it again. =)

**Comment by MarianaSouza** [comment]
> Hi Mariana, I'm reviewing it again. =)

Hey @helgakern :) 
The PR was already merged, so you can't approve it anymore. Thanks for answering back tough ;)

**Pull request merged**
