### PR TITLE
Added a new course section to include javascript content

### PR DESCRIPTION
**Pull request by helgakern**
I added a new course section to the repository to include all JavaScript related content. A link to the JS Codecademy course, my first contact with the language, was added to the course. Fix issue #5.

### CODE REVIEW

**Comment by MarianaSouza** [comment]
Hi @helgakern ,
Thanks for creating this PR. Is it already ready for review?
If so, please always remember to select your Reviewers and Assign Yourself as responsible for the PR.
Also, please provide a description of your PR where you mention the issue, it is never done on the title.
This is an image highlighting the areas you should work on a little bit:

helga-pr-feedback

As a good example, please also refer to the image attached to the repository:
https://github.com/MarianaSouza/web-dev-path

Thanks! :)

**Review by MarianaSouza — CHANGES_REQUESTED** [review]
Hi @helgakern ,
Thanks for creating this PR. Is it already ready for review?
If so, please always remember to select your Reviewers and Assign Yourself as responsible for the PR.
Also, please provide a description of your PR where you mention the issue, it is never done on the title.
This is an image highlighting the areas you should work on a little bit:

helga-pr-feedback

As a good example, please also refer to the image attached to the repository:
https://github.com/MarianaSouza/web-dev-path

Finally, I see your PR only adds a title on the README. I'd say that it would be nicer to have a course suggestion as well.

Thanks! :)

**Comment by helgakern** [comment]
I added a link do Learn JavaScript by Codecademy. It was my first contact with the language and I started learning from there.  It is a very clear and didactic course.

**Comment by MarianaSouza** [comment]
> I added a link do Learn JavaScript by Codecademy. It was my first contact with the language and I started learning from there. It is a very clear and didactic course.

Such a nice course! @helgakern , can you please add the above course description to the PR description?
Below what you already have there, you could say: "A link to the JS Codecademy course, my first contact with the language, was added to the course." It would be even more perfect if you wrap the JS Codecademy course with the actual link so that people who review your PR have access to the course without checking the commit.

**Comment by MarianaSouza** [comment]
Hey @helgakern :)
Thanks for fixing your PR description ;)
Could you please pull from master to your branch and commit it so that we solve the conflict that is preventing the merge?
Please let me know if you have any questions!

**Comment by helgakern** [comment]
Hi Mariana,
I pulled from master to my branch and commited, but I got a message saying that everything was up to date.
Let me know if it fixed or not.
Thanks!

**Comment by MarianaSouza** [comment]
> Hi Mariana,
> I pulled from master to my branch and commited, but I got a message saying that everything was up to date.
> Let me know if it fixed or not.
> Thanks!

Hey @helgakern 

You need to commit here to the PR :)
The process is:

1. Since your branch is too different for master (because we already added more content there after your PR), you need to go to your branch (git checkout section/adding-javascript) and pull from master there (git pull origin master)

2. You'll see your branch is going to receive the new data from master. Then, you commit to this PR saying something like "pulling from master to solve conflicts".

3 By doing so, the message we see now saying "This branch has conflicts that must be resolved" will disappear, which means the PR is ready to be approved and merged without conflicts.

Does that make sense? Please let me know if you have more questions.

**Comment by MarianaSouza** [comment]
I'm adding all of you as reviewers to this PR so that you can check the process to solve a small conflict ;)
@kaileegiles , @CarolDill , @rebecatschiedel, and @ZahraB21

**Comment by ZahraB21** [comment]
Sounds Good. Will wait until the conflict is resolved a a new commit is sent. Thanks @MarianaSouza

**Comment by MarianaSouza** [comment]
> Sounds Good. Will wait until the conflict is resolved and a new commit is sent. Thanks @MarianaSouza

Np! Next time we see a conflict in our PR's, @ZahraB21, I guess we should record a video showing how to do that pull from the master on our branch and commit it. What do you think?

**Comment by helgakern** [comment]
Thank you, Mariana.
I think now everything is good to go. 
Again, let me know how it went.
=)

**Comment by MarianaSouza** [comment]
> Thank you, Mariana.
> I think now everything is good to go.
> Again, let me know how it went.
> =)

You solved the conflict, girl! Good job!
I've just noticed that there is only a minor issue with your link markup, @helgakern :

section-markup
https://github.com/MarianaSouza/web-dev-path/tree/section/adding-javascript

Could please fix it by removing the space between the [] and the {} and commit it again?

**Comment by helgakern** [comment]
Almost there... =)
Now is it ok?

**Comment by MarianaSouza** [comment]
> Almost there... =)
> Now is it ok?

Yep, thanks! great job! 
You can always check how your commits are affecting the project by checking the branch link: 
https://github.com/MarianaSouza/web-dev-path/tree/section/adding-javascript

image

**Review by MarianaSouza — APPROVED** [review]

**Pull request merged**
