### PR TITLE
Adding a Header Image to the repository.

### LINKED ISSUE #27: Adding a Header Image to the repository
I've created a simple logo for our Slack channel this week and also this wider one (attached) that I think we could add to the top of our repo as a header before the main h1 title, what do you think? I've already added a similar image (a narrower version) to our [social media preview](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-your-repositorys-social-media-preview) so that when we share the repo link, we see something more customized.

To do so, we would have to save this attached image into our images-web-dev-path folder and, then, add some HTML and inline CSS as described here: https://stackoverflow.com/questions/12090472/github-readme-md-center-image. If you're up to the challenge, remove the other assignees from the issue, leave a comment saying this task is yours, and go for it! :D

Let me know if you have any questions! ;)

web-dev-path-github

<hr /> 

_HOT TIP:
When submitting a Pull Request to solve an issue, mention the issue number on the PR description (not on the title) so that they both get linked.
You can use something like "Solves #26", "Referent to the issue #27", or Closes #27. By using Closes and the issue number, GitHub will automatically close the issue when the PR that is addressing it is merged into the master._

### PR DESCRIPTION
**Pull request by rebecatschiedel**
Added web-dev-logo.png to images file. Added Logo as a header to the repository.

This Pr Closes #27.

### CODE REVIEW

**Review by ZahraB21 — CHANGES_REQUESTED** [review]
Thanks @rebecatschiedel for the PR.

It would be great if you could merge your master with the latest version of Mariana's since I noticed you have duplicate WordPress and the Python section is missing as well.

**Comment by rebecatschiedel** [comment]
Thank you for letting me know @ZahraB21 !!
Just updated my branch! :)

**Review by helgakern — APPROVED** [review]
Great job, Rebeca. It looks good to me. =)

**Review by MarianaSouza — CHANGES_REQUESTED** [review]
Thanks so much for this PR, @rebecatschiedel !

I've realized that the image I provided is too big for a header:

image

Would you mind to update the image for this narrower one, please?

web-dev-path-logo

Also, I think if we wrap the image in a div and add some inline CSS border-radius, maybe 5px, it would look more like a header. Could you please thy that?

**Comment by rebecatschiedel** [comment]
Hey Girls, 

I have a problem:
the inline style for the border-radius worked fine on VS Code Markdown Preview, both with the <header> and the <div> tags, but it does not work on Github. 
Any suggestions?

**Comment by MarianaSouza** [comment]
> Hey Girls,
> 
> I have a problem:
> the inline style for the border-radius worked fine on VS Code Markdown Preview, both with the
> 
> and the
> tags, but it does not work on Github.
> Any suggestions?

Hey @rebecatschiedel ,

My bad, I misguided you. It seems there is no way to add CSS on Github through style because it gets sanitized:

https://github.community/t/github-flavored-markdown-doesnt-render-css-styles-inside-a-html-block/126258

GitHub still accepts some styles such as  align="value" but not from CSS (style= ). I will change that image on [Photopea and](https://www.photopea.com/) I'll send it ready for you one last time ;)

**Comment by CarolDill** [comment]
Hi girls!

I see the smaller image, but as per the conversation, is not totally ready yet, right?

**Comment by MarianaSouza** [comment]
Hey  @rebecatschiedel ,
I'm attaching the round corner image :D
Thanks!

web-dev-path-logo-round

**Comment by rebecatschiedel** [comment]
All done!! :)

**Review by MarianaSouza — APPROVED** [review]
That looks awesome, @rebecatschiedel ! Thanks so much!

**Review by MarianaSouza — APPROVED** [review]

**Review by MarianaSouza — APPROVED** [review]

**Review by MarianaSouza — APPROVED** [review]

**Comment by MarianaSouza** [comment]
> That looks awesome, @rebecatschiedel ! Thanks so much!

Hey @ZahraB21 ! It's over you ;)

**Review by ZahraB21 — APPROVED** [review]

**Comment by ZahraB21** [comment]
Good to go. Thank you @rebecatschiedel

**Pull request merged**
